apiVersion: v1
kind: Secret
metadata:
  name: kafka-handlers
stringData:
  username: "{{ .Values.connection.username }}"
  password: "{{ .Values.connection.password }}"
  sasl: plaintext
  tls: enable
